name: Release Build

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run Spotless Check
        run: ./gradlew spotlessCheck

      - name: Run Unit Tests
        run: ./gradlew test

      # Note: Instrumented tests are skipped in CI as they're flaky in managed devices
      # Run them locally with: ./gradlew pixel6Api34DebugAndroidTest

  build-and-upload:
    name: Build and Upload Release APK
    needs: test
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Extract version from tag
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "name=$VERSION" >> $GITHUB_OUTPUT
          # Extract version code from build.gradle.kts and increment
          CURRENT_CODE=$(grep "versionCode = " app/build.gradle.kts | sed 's/.*versionCode = //' | sed 's/[^0-9]*//g')
          NEW_CODE=$((CURRENT_CODE + 1))
          echo "code=$NEW_CODE" >> $GITHUB_OUTPUT

      - name: Decode Keystore
        env:
          ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
        run: |
          if [ -n "$ANDROID_KEYSTORE_BASE64" ]; then
            echo "$ANDROID_KEYSTORE_BASE64" | base64 -d > ${{ github.workspace }}/release.keystore
          else
            echo "ERROR: ANDROID_KEYSTORE_BASE64 secret is not set"
            exit 1
          fi

      - name: Build Release APK
        env:
          RELEASE_STORE_FILE: ${{ github.workspace }}/release.keystore
          RELEASE_STORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          RELEASE_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          RELEASE_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
          VERSION_NAME: ${{ steps.version.outputs.name }}
          VERSION_CODE: ${{ steps.version.outputs.code }}
          CI: true
        run: ./gradlew :app:assembleRelease -PversionName=$VERSION_NAME -PversionCode=$VERSION_CODE

      - name: Upload Release APK to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: app/build/outputs/apk/release/*.apk
          token: ${{ secrets.GITHUB_TOKEN }}